// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGPCUArYWfjeDI-T1mDamjhf1hdKLVj_o',
    appId: '1:733301548359:web:778fa541d996967bc91862',
    messagingSenderId: '733301548359',
    projectId: 'moneycare-606f9',
    authDomain: 'moneycare-606f9.firebaseapp.com',
    storageBucket: 'moneycare-606f9.firebasestorage.app',
    measurementId: 'G-B2LZ4604BE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBInGjrJ--Am66WZgDpmcif4K7kH3-6xZI',
    appId: '1:733301548359:android:900950099cf5af92c91862',
    messagingSenderId: '733301548359',
    projectId: 'moneycare-606f9',
    storageBucket: 'moneycare-606f9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHNO38blxT9kUa4WZr7EjNnX0eKCaeH8o',
    appId: '1:733301548359:ios:dd014a0adc7a3cb4c91862',
    messagingSenderId: '733301548359',
    projectId: 'moneycare-606f9',
    storageBucket: 'moneycare-606f9.firebasestorage.app',
    iosBundleId: 'com.htd.org.moneyCare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHNO38blxT9kUa4WZr7EjNnX0eKCaeH8o',
    appId: '1:733301548359:ios:dd014a0adc7a3cb4c91862',
    messagingSenderId: '733301548359',
    projectId: 'moneycare-606f9',
    storageBucket: 'moneycare-606f9.firebasestorage.app',
    iosBundleId: 'com.htd.org.moneyCare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGPCUArYWfjeDI-T1mDamjhf1hdKLVj_o',
    appId: '1:733301548359:web:26d919e64a932e10c91862',
    messagingSenderId: '733301548359',
    projectId: 'moneycare-606f9',
    authDomain: 'moneycare-606f9.firebaseapp.com',
    storageBucket: 'moneycare-606f9.firebasestorage.app',
    measurementId: 'G-B59XVDNSP3',
  );
}
